<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Interpretation.aspx.cs" Inherits="Designer_Interpretation"
    MasterPageFile="~/MyMasterPage.master" Title="Редактор интерпретации" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div>
        <asp:ScriptManager ID="ScriptManager1" runat="server"/>
        
        <asp:HyperLink ID="hlGotoTest" runat="server" 
            NavigateUrl="~/Designer/EditTest.aspx">Перейти к тесту</asp:HyperLink>
        <asp:Label ID="Label3" runat="server" Width="50px" ></asp:Label>
        <asp:HyperLink ID="hlGotoBlocks" runat="server" 
            NavigateUrl="~/Designer/TestBlocks.aspx">Перейти к блокам</asp:HyperLink>
        <br /><br />
        <asp:Label ID="Label1" runat="server" Text="Текст интерпетации"></asp:Label>
        <br />
        
        <asp:TextBox ID="tbText" runat="server" Height="300px" TextMode="MultiLine" Width="100%"
            BorderColor="#0033CC" BorderStyle="Solid"></asp:TextBox>
        <br />
        <ajaxToolkit:HtmlEditorExtender ID="htmlEditorExtender2" TargetControlID="tbText"
            runat="server" DisplaySourceTab="True" OnImageUploadComplete="ajaxFileUpload_OnUploadComplete">
            <Toolbar>
                <ajaxToolkit:Bold />
                <ajaxToolkit:Italic />
                <ajaxToolkit:Underline />
                <ajaxToolkit:HorizontalSeparator />
                <ajaxToolkit:JustifyLeft />
                <ajaxToolkit:JustifyCenter />
                <ajaxToolkit:JustifyRight />
                <ajaxToolkit:JustifyFull />
                <ajaxToolkit:CreateLink />
                <ajaxToolkit:UnLink />
                <ajaxToolkit:InsertImage />
                <ajaxToolkit:FontNameSelector />
                <ajaxToolkit:FontSizeSelector />
                <ajaxToolkit:InsertOrderedList />
                <ajaxToolkit:InsertUnorderedList />
                <ajaxToolkit:InsertHorizontalRule />
                <ajaxToolkit:HorizontalSeparator />
            </Toolbar>
        </ajaxToolkit:HtmlEditorExtender>
        <p>
            <%--<asp:CheckBox runat="server" Text="данная интерпретация является 'активной угрозой'" ID="cboxActiveThreat"/>--%>
            Вид интерпретации
            <asp:DropDownList ID="ddlInterKind" runat="server">
                <asp:ListItem Value="0">&lt;обычный&gt;</asp:ListItem>
                <asp:ListItem Value="1">Активная угроза</asp:ListItem>
                <asp:ListItem Value="2">Потенциал</asp:ListItem>
        </asp:DropDownList>
        </p>
        <p>
            &nbsp;</p>
        <hr/>
        <asp:Label ID="Label2" runat="server" Text="Условия возникновения интерпретации"></asp:Label>
        <br />
        <asp:GridView ID="gridConditions" runat="server" AutoGenerateColumns="False" DataKeyNames="id"
            DataSourceID="InterConditions_LDS" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
            Width="100%">
            <Columns>
                <asp:TemplateField HeaderText="Шкала" SortExpression="scale_id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList1" Width="100%" runat="server" SelectedValue='<%# Bind("scale_id") %>'
                            DataSourceID="Scales_SQL" DataTextField="name" DataValueField="id">
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Scale.name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="min_value" HeaderText="Нижняя граница" SortExpression="min_value">
                    <ControlStyle Width="97%" />
                </asp:BoundField>
                <asp:BoundField DataField="max_value" HeaderText="Верхняя граница" SortExpression="max_value">
                    <ControlStyle Width="97%" />
                </asp:BoundField>
                <asp:TemplateField HeaderText="Тип" SortExpression="range_type">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlType" Width="100%" runat="server" SelectedValue='<%# Bind("range_type") %>'>
                            <asp:ListItem Value="1">абсолютное значение</asp:ListItem>
                            <asp:ListItem Value="2">рейтинг</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("ConditionRangeType.name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <EditRowStyle BorderColor="Red" BorderStyle="Solid" />
        </asp:GridView>
        <asp:LinqDataSource ID="InterConditions_LDS" runat="server" ContextTypeName="TesterDataClassesDataContext"
            EntityTypeName="" TableName="inter_conditions" Where="inter_id == @inter_id"
            EnableDelete="True" EnableUpdate="True">
            <WhereParameters>
                <asp:QueryStringParameter DefaultValue="0" Name="inter_id" QueryStringField="InterID"
                    Type="Int32" />
            </WhereParameters>
        </asp:LinqDataSource>
        <asp:SqlDataSource ID="Scales_SQL" runat="server" ConnectionString="<%$ ConnectionStrings:tester_dataConnectionString %>"
            SelectCommand="select s.name, s.id
from interpretation i
inner join scales s on i.test_id=s.test_id
where i.id = @iid">
            <SelectParameters>
                <asp:QueryStringParameter Name="iid" Type="Int32" QueryStringField="InterID" DefaultValue="0" />
            </SelectParameters>
        </asp:SqlDataSource>
        <br />
        <asp:Button ID="btnAdd" runat="server" Text="Добавить" OnClick="btnAdd_Click" />
        <hr />
        <asp:Button ID="btnOk" runat="server" Text="OK" OnClick="btnOk_Click" Width="85px" />
        <br />
        <br />
    </div>
</asp:Content>
